apiVersion: v1
kind: Secret
metadata:
  name: thomosis-auth-secret
type: Opaque
data:
  DB_HOST: ZGI=   # base64-encoded value for "db"
  DB_PASSWORD: YlgteXktc2Vjb25kLXB3  # base64-encoded value for "my-secret-pw"

