apiVersion: v1
kind: ConfigMap
metadata:
  name: thomosis-ui-config
data:
  AUTH_HOST: thomosis-auth
  AUTH_PORT: "8080"
  WEATHER_HOST: thomosis-weather
  WEATHER_PORT: "5000"
  REDIS_USER: redis
  REDIS_PASSWORD: redis
